### ISSUE TITLE
[Feature Request] Add Obsidian Tasks style completed date

### ISSUE THREAD

**Issue by aventuraviper** [wesmoncrief/obsidian-todoist-text#1]
Hi

Great Plugin - thanks for making it.

Would it be possible to add an obsidian tasks compatible completed date when checking a task off?

Thanks

**Comment by wesmoncrief** [comment]
Hey @aventuraviper ,

Thanks for filing, and glad you like this plugin!

Hmm, so I would probably like to avoid tangling this plugin with obsidian tasks - for example, if that plugin were to make a breaking change, it could suddenly break the way that this plugin interacts with it.

But I think you could get what you want via some other method. In particular, I assume that you want `<Cmd>-<Enter>` to do two things: check off the task on Todoist (via the `Todoist Text: Toggle todoist task` command), and check off the task via obsidian tasks (via the `Tasks: Toggle task done` command), which would add the date at the end of the task.

So you could actually write a very tiny plugin that just registers a new command. That command itself would just call this plugin's command, then call the Tasks plugin command. Here's an example of how to call another plugin's command - https://github.com/wesmoncrief/obsidian-todoist-text/blob/master/main.ts#L27-L36

I actually would have expected that if you assign a single shortcut to multiple commands, Obsidian would invoke all of those commands. Could be worth filling a request to obsidian about that

**Comment by aventuraviper** [comment]
Hi @wesmoncrief 

Thank you for the detailed response considering this feature.

However, I am not sure how this would be entangling the plugins? I envisaged an option in obsidian-todoist-text to enable this and if checked it would add a function to `Todoist Text: Toggle todoist task` command that simply adds the completion date in the form `✅ YYYY-MM-DD` at the end of the task after completing the rest of the `Todoist Text: Toggle todoist task` function.

I shall look into creating another plugin to add this.

**Comment by wesmoncrief** [comment]
So something that could happen is that a new version of Obsidian Tasks could add a new setting that allows people to use a customized completion date format - e.g., so that you could use `MM-DD-YY` instead of the `✅ YYYY-MM-DD`.

If they offer this setting, then all of sudden the Todoist plugin would not be respecting their setting correctly, resulting in a broken experience.

The other option for implementation would be to have Todoist invoke the Obsidian Tasks plugin command (which is what I mentioned in my earlier message). This again could be broken if Obsidian Tasks changes the name of its command.

Happy to help you creating the plugin if you run into any issues!

**Comment by wesmoncrief** [comment]
@aventuraviper  I'll go ahead and close this, but feel free to reach out here if you have any issues with creating the plugin! Happy to help
