### ISSUE TITLE
subtasks don't render

### ISSUE THREAD

**Issue by wesmoncrief** [wesmoncrief/obsidian-todoist-text#12]
should probably end up being rendered with an indent type of thing

**Comment by madajczyk** [comment]
@wesmoncrief - this seemed like a decent feature improvement that I could try tackling.  I was actually able to get subtasks working already in my fork (see below), but still need to make some more tweaks.  Specifically, since I found that subtasks can also have their own subtasks, I need to extend my changes to allow for recursion through those as well.

![image](https://user-images.githubusercontent.com/1332880/209485362-6bc51f93-8d6f-4299-816d-e865ca476449.png)

As I was investigating this, I realized it's possible some folks might not want subtasks to get added.  With that, I thought it might be good to add a setting to enable/disable subtasks, as well as maybe add a max recursion depth.  I'd be curious as to your thoughts on this idea.

Also, if I'm overstepping here, please let me know.  I thought this was a cool little plugin, and I've been meaning to brush up on TypeScript.  Seemed like a good place to give back a little.

**Comment by wesmoncrief** [comment]
Hey,

This sounds awesome! Would love it if you were able to make this change!

Agreed it should be optional, and I'd say that defaulting to showing subtasks would make sense.

I don't think we'd need a user-specified max depth input. From the website, it looks like the max depth is 4, and I'd be surprised if there's a real use-case for wanting to only go X layers deep.

Feel free to open a PR. The only thing I'd request is a comment in the PR overview saying what you've tested manually (as there's not any UI tests here).

**Comment by madajczyk** [comment]
Sounds good.  Thanks for advising on what the max depth was, I probably should have looked into what that limit was first before jumping ahead to a setting.

I've still got some more work to do on this before it's ready for PR, but I'll make sure to include the details you need.  If anything else pops up, I'll follow up here.
